version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
variables:
  NPM_TOKEN: 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
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install && rm -rf ./dist && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID: gitee-go
        script: |-
          npm install && rm -rf ./dist && npm run build
          npm install -g @jsdevtools/npm-publish
          npm-publish --token=$NPM_TOKEN ./package.json
permissions:
  - role: admin
    members: []
